[pytest]
testpaths = tests
python_files = test_*.py
addopts = --alluredir=allure-results
python_functions = test_*
markers =
    smoke: critical smoke tests
    regression: full regression tests
    auth: auth-related tests
    posts: posts-related tests
    users: users-related tests
    negative: negative scenarios